- .npmrc
- README.md
- __tests__/unit/logic.service.test.ts
- package-lock.json
- package.json
- src/controllers/execute.ts
Fixed issue where the imported rule library is actually stored in the /lib subfolder. Now the published rules will pull successfully.
> BUG: Fix import reference

- package-lock.json
- package.json
- src/helpers/determineOutcome.ts
Fix determineOutcome to work with the banded rule outcomes.
> BUG: Fix determineOutcome method

- src/controllers/execute.ts
Added error handling to expect some thrown errors from the rule code; Added error handling around config management.
> BUG: Added error handling

- .github/workflows/milestone.yml
- .github/workflows/release.yml
- Dockerfile
This commit consists of cleanup and refactor of the docker files and adding the release workflows.
> feat: Release workflows added and Docker file reform

- package-lock.json
- package.json
- src/controllers/execute.ts
This PR adds the calculation of the duration execution of the rule
Related to https://github.com/frmscoe/General-Issues/issues/153
> Performance calculation

- src/controllers/execute.ts
Relate to https://github.com/frmscoe/General-Issues/issues/153
> chore: better end time not need to declare

- package-lock.json
- package.json
- src/controllers/execute.ts
We were sending the default error result regardless of outcome.
> Send correct rule result 

- src/controllers/execute.ts
Related to: https://github.com/frmscoe/General-Issues/issues/178
> feat: propagate traceParent to next processor in chain

- src/apm.ts
- src/controllers/execute.ts
- src/index.ts
- Also include rule id as part of span
> fix: auto spans for supported technologies

- package-lock.json
- package.json
- src/apm.ts
- src/controllers/execute.ts
Related to: https://github.com/frmscoe/General-Issues/issues/238
> refactor: use lib apm service

- src/controllers/execute.ts
Also added log if error when retrieving config.
> bug: double serialization of response when config error

- Dockerfile
- __tests__/unit/logic.service.test.ts
- package-lock.json
- package.json
Related to https://github.com/frmscoe/General-Issues/issues/261
> test: use proto-buf intercoms lib

- package-lock.json
- package.json
- src/controllers/execute.ts
Related to: https://github.com/frmscoe/General-Issues/issues/281
The description is removed entirely as well on both cases.
> feat: remove reason on happy path

- .github/workflows/milestone.yml
- .github/workflows/release.yml
- Dockerfile
- package.json
> chore: Bump version for release

- package-lock.json
- package.json
- src/config.ts
- src/index.ts
Related to : https://github.com/frmscoe/General-Issues/issues/310
> feat: use networkmap for nats routing

- src/config.ts
- src/index.ts
- src/interfaces/iConfig.ts
In Relation to: https://github.com/frmscoe/General-Issues/issues/383
> feat: added multiple CPU Support

- Dockerfile
Fixed a bug in relation to: https://github.com/frmscoe/General-Issues/issues/383
> bug: maxcpu docker

- .github/dependabot.yml
- .github/workflows/codacy.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/milestone.yml
- .github/workflows/njsscan.yml
- .github/workflows/node.js.yml
- .github/workflows/release.yml
- .npmignore
- Dockerfile
- README.md
Related to https://github.com/frmscoe/General-Issues/issues/115
> Chore: add license header

- .github/workflows/conventional-commits.yml
- .github/workflows/dco-check.yaml
- .github/workflows/gpg-verify.yml
- .github/workflows/milestone.yml
- .github/workflows/release.yml
> feat: Add new workflows

- package.json
> feat: dependency version bump to next

- package-lock.json
- package.json
> build: bump rule and lib ver
